name: Bench

on: push

jobs:
  bench:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: 'nix develop -c bash -euxo pipefail {0}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          install_url: https://releases.nixos.org/nix/nix-2.12.0/install

      - name: Install Elan
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf > elan.sh
          chmod +x elan.sh
          ./elan.sh -y
          export PATH=$HOME/.local/bin:$HOME/.elan/bin:$PATH

      - name: Run Benchmarking Suite
        run: |
          export PATH=$HOME/.local/bin:$HOME/.elan/bin:$PATH
          cd 1-runs/1-SKELETON
          bash ci-worker.sh

      - name: Show Temci Report
        run: |
          export PATH=$HOME/.local/bin:$HOME/.elan/bin:$PATH
          cat 1-runs/1-SKELETON/outputs/temci-report.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            1-runs/1-SKELETON/outputs/temci-report.txt


