name: Bench

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: 'nix develop -c bash -euxo pipefail {0}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v18
        with:
          install_url: https://releases.nixos.org/nix/nix-2.12.0/install

      - name: Run Benchmarking Suite
        run: |
          cd 1-runs/1-SKELETON
          bash ci-worker.sh

      - name: Show Temci Report
        run: |
          cat 1-runs/1-SKELETON/outputs/temci-report.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            1-runs/1-SKELETON/outputs/temci-report.txt


